### ISSUE TITLE
Option for setting the (relative) bubble width.

### ISSUE THREAD

**Issue by jjohanss** [kethinov/BubblePainter#19]
I for one use Messages covering the whole desktop and in such a state the default width of the bubbles (60%?) can look a bit stupid. Hence I'd like to have wider bubbles.

**Comment by kethinov** [comment]
Sure, I can look into that.

**Comment by kethinov** [comment]
Download version 2.1.0 to try out this new feature.

**Comment by jjohanss** [comment]
Works like a charm. Thanks.
