### ISSUE TITLE
macOS Sierra support

### ISSUE THREAD

**Issue by kethinov** [kethinov/BubblePainter#31]
This is untested in Sierra. There may be unaccounted for bugs.

**Comment by michaelrjohnson** [comment]
Just installed on 10.12.2. Seems to run without issue.

**Comment by kethinov** [comment]
That is good to know!

I just assumed it would break because I had not tested it yet. Haven't been using Messages.app for IM for a while so this app hasn't gotten the love that it used to.

Guess I'll close this then!
