### ISSUE TITLE
Possibly broken in 10.13.3

### ISSUE THREAD

**Issue by Resetz** [kethinov/BubblePainter#34]
I do the `csrutil enable` and reboot. I try the bubble painter again and it does not work

**Comment by kethinov** [comment]
Looks like it may be broken 10.13.3 (and possibly some earlier versions).

I don't have time to investigate right now, but if anyone gets to it before me, pull requests with a fix are welcome!

**Comment by Resetz** [comment]
Sorry my mistake
I did the wrong thing
